package instructions

// Extracted from: https://gbdev.io/gb-opcodes/Opcodes.json

type Mnemonic string

const (
	NOP        Mnemonic = "NOP"
	LD         Mnemonic = "LD"
	INC        Mnemonic = "INC"
	DEC        Mnemonic = "DEC"
	RLCA       Mnemonic = "RLCA"
	ADD        Mnemonic = "ADD"
	RRCA       Mnemonic = "RRCA"
	STOP       Mnemonic = "STOP"
	RLA        Mnemonic = "RLA"
	JR         Mnemonic = "JR"
	RRA        Mnemonic = "RRA"
	DAA        Mnemonic = "DAA"
	CPL        Mnemonic = "CPL"
	SCF        Mnemonic = "SCF"
	CCF        Mnemonic = "CCF"
	HALT       Mnemonic = "HALT"
	ADC        Mnemonic = "ADC"
	SUB        Mnemonic = "SUB"
	SBC        Mnemonic = "SBC"
	AND        Mnemonic = "AND"
	XOR        Mnemonic = "XOR"
	OR         Mnemonic = "OR"
	CP         Mnemonic = "CP"
	RET        Mnemonic = "RET"
	POP        Mnemonic = "POP"
	JP         Mnemonic = "JP"
	CALL       Mnemonic = "CALL"
	PUSH       Mnemonic = "PUSH"
	RST        Mnemonic = "RST"
	PREFIX     Mnemonic = "PREFIX"
	ILLEGAL_D3 Mnemonic = "ILLEGAL_D3"
	RETI       Mnemonic = "RETI"
	ILLEGAL_DB Mnemonic = "ILLEGAL_DB"
	ILLEGAL_DD Mnemonic = "ILLEGAL_DD"
	LDH        Mnemonic = "LDH"
	ILLEGAL_E3 Mnemonic = "ILLEGAL_E3"
	ILLEGAL_E4 Mnemonic = "ILLEGAL_E4"
	ILLEGAL_EB Mnemonic = "ILLEGAL_EB"
	ILLEGAL_EC Mnemonic = "ILLEGAL_EC"
	ILLEGAL_ED Mnemonic = "ILLEGAL_ED"
	DI         Mnemonic = "DI"
	ILLEGAL_F4 Mnemonic = "ILLEGAL_F4"
	EI         Mnemonic = "EI"
	ILLEGAL_FC Mnemonic = "ILLEGAL_FC"
	ILLEGAL_FD Mnemonic = "ILLEGAL_FD"
	RLC        Mnemonic = "RLC"
	RRC        Mnemonic = "RRC"
	RL         Mnemonic = "RL"
	RR         Mnemonic = "RR"
	SLA        Mnemonic = "SLA"
	SRA        Mnemonic = "SRA"
	SWAP       Mnemonic = "SWAP"
	SRL        Mnemonic = "SRL"
	BIT        Mnemonic = "BIT"
	RES        Mnemonic = "RES"
	SET        Mnemonic = "SET"
)
