// Code generated by "stringer -type=Interrupt -output=zz_generated_strings.go"; DO NOT EDIT.

package cpu

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VBLANK-1]
	_ = x[LCD_STAT-2]
	_ = x[TIMER-4]
	_ = x[SERIAL-8]
	_ = x[JOYPAD-16]
}

const (
	_Interrupt_name_0 = "VBLANKLCD_STAT"
	_Interrupt_name_1 = "TIMER"
	_Interrupt_name_2 = "SERIAL"
	_Interrupt_name_3 = "JOYPAD"
)

var (
	_Interrupt_index_0 = [...]uint8{0, 6, 14}
)

func (i Interrupt) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _Interrupt_name_0[_Interrupt_index_0[i]:_Interrupt_index_0[i+1]]
	case i == 4:
		return _Interrupt_name_1
	case i == 8:
		return _Interrupt_name_2
	case i == 16:
		return _Interrupt_name_3
	default:
		return "Interrupt(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
