// Code generated by "stringer -type=CartridgeType -output=zz_generated_strings.go"; DO NOT EDIT.

package cartridge

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ROM_ONLY-0]
	_ = x[MBC1-1]
	_ = x[MB1_RAM-2]
	_ = x[MBC1_RAM_BATTERY-3]
	_ = x[MBC2-5]
	_ = x[MBC2_BATTERY-6]
	_ = x[ROM_RAM-8]
	_ = x[ROM_RAM_BATTERY-9]
	_ = x[MMM01-11]
	_ = x[MMM01_RAM-12]
	_ = x[MMM01_RAM_BATTERY-13]
	_ = x[MBC3_TIMER_BATTERY-15]
	_ = x[MBC3_TIMER_RAM_BATTERY-16]
	_ = x[MBC3-17]
	_ = x[MBC3_RAM-18]
	_ = x[MBC3_RAM_BATTERY-19]
	_ = x[MBC5-25]
	_ = x[MBC5_RAM-26]
	_ = x[MBC5_RAM_BATTERY-27]
	_ = x[MBC5_RUMBLE-28]
	_ = x[MBC5_RUMBLE_RAM-29]
	_ = x[MBC5_RUMBLE_RAM_BATTERY-30]
	_ = x[MBC6-32]
	_ = x[MBC7_SENSOR_RUMBLE_RAM_BATTERY-34]
	_ = x[POCKET_CAMERA-252]
	_ = x[BANDAI_TAMA5-253]
	_ = x[HUC3-254]
	_ = x[HUC1_RAM_BATTERY-255]
}

const (
	_CartridgeType_name_0 = "ROM_ONLYMBC1MB1_RAMMBC1_RAM_BATTERY"
	_CartridgeType_name_1 = "MBC2MBC2_BATTERY"
	_CartridgeType_name_2 = "ROM_RAMROM_RAM_BATTERY"
	_CartridgeType_name_3 = "MMM01MMM01_RAMMMM01_RAM_BATTERY"
	_CartridgeType_name_4 = "MBC3_TIMER_BATTERYMBC3_TIMER_RAM_BATTERYMBC3MBC3_RAMMBC3_RAM_BATTERY"
	_CartridgeType_name_5 = "MBC5MBC5_RAMMBC5_RAM_BATTERYMBC5_RUMBLEMBC5_RUMBLE_RAMMBC5_RUMBLE_RAM_BATTERY"
	_CartridgeType_name_6 = "MBC6"
	_CartridgeType_name_7 = "MBC7_SENSOR_RUMBLE_RAM_BATTERY"
	_CartridgeType_name_8 = "POCKET_CAMERABANDAI_TAMA5HUC3HUC1_RAM_BATTERY"
)

var (
	_CartridgeType_index_0 = [...]uint8{0, 8, 12, 19, 35}
	_CartridgeType_index_1 = [...]uint8{0, 4, 16}
	_CartridgeType_index_2 = [...]uint8{0, 7, 22}
	_CartridgeType_index_3 = [...]uint8{0, 5, 14, 31}
	_CartridgeType_index_4 = [...]uint8{0, 18, 40, 44, 52, 68}
	_CartridgeType_index_5 = [...]uint8{0, 4, 12, 28, 39, 54, 77}
	_CartridgeType_index_8 = [...]uint8{0, 13, 25, 29, 45}
)

func (i CartridgeType) String() string {
	switch {
	case i <= 3:
		return _CartridgeType_name_0[_CartridgeType_index_0[i]:_CartridgeType_index_0[i+1]]
	case 5 <= i && i <= 6:
		i -= 5
		return _CartridgeType_name_1[_CartridgeType_index_1[i]:_CartridgeType_index_1[i+1]]
	case 8 <= i && i <= 9:
		i -= 8
		return _CartridgeType_name_2[_CartridgeType_index_2[i]:_CartridgeType_index_2[i+1]]
	case 11 <= i && i <= 13:
		i -= 11
		return _CartridgeType_name_3[_CartridgeType_index_3[i]:_CartridgeType_index_3[i+1]]
	case 15 <= i && i <= 19:
		i -= 15
		return _CartridgeType_name_4[_CartridgeType_index_4[i]:_CartridgeType_index_4[i+1]]
	case 25 <= i && i <= 30:
		i -= 25
		return _CartridgeType_name_5[_CartridgeType_index_5[i]:_CartridgeType_index_5[i+1]]
	case i == 32:
		return _CartridgeType_name_6
	case i == 34:
		return _CartridgeType_name_7
	case 252 <= i && i <= 255:
		i -= 252
		return _CartridgeType_name_8[_CartridgeType_index_8[i]:_CartridgeType_index_8[i+1]]
	default:
		return "CartridgeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
